name: Build and publish SCS image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/demo-app-scs

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build SCS image
        run: |
          docker build \
            -f my-app-web/Dockerfile \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sgc-test \
            .

      - name: Push SCS image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sgc-test
